# Generated by Django 4.0.2 on 2022-03-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_transaction_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
